name: CI Full Stack (Backends + Frontend)

on:
  push:
  pull_request:

jobs:
  test-python:
    name: Test Python Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: BackEnd/SQL  

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Requirements.txt

      - name: Run pytest
        env:
          SQLALCHEMY_DATABASE_URL: "sqlite:///./test.db"
        run: |
          python -m pytest tests/routes --html=pytest_report.html --self-contained-html -v

  test-node-mongo:
    name: Test Node.js MongoDB API
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: BackEnd/MongoDB  

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Jest
        run: npm test

  test-node-verifier-issuer:
    name: Test Node.js Verifier/Issuer API
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: BackEnd/VerifierIssuerAPI  

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Jest
        run: npm test

  test-frontend:
    name: Test Frontend (Vitest)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: FrontEnd  

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Vitest
        run: npx vitest --ui
